### PR TITLE
Update mso_schema_template_bd.py

### PR DESCRIPTION
**Pull request by RonaldBlom**
fix issue #216 
https://github.com/CiscoDevNet/ansible-mso/issues/216

### CODE REVIEW

**Comment by lhercot** [comment]
I am closing this PR as PR #223 is fixing the same issue.
Thanks for the contribution feel free to open another PR for other issues you want to contribute on.

**Comment by RonaldBlom** [comment]
@lhercot, I just updated my modules. But the issue still exists. So my fix was solving this better. Could you please take a look at this again? Thanks and regards, Ronald Blom

**Comment by lhercot** [comment]
Can you explain the problem with the current fix?

Your solution look like it would not work if the module is used to change an already disabled unicast routing to try to enable it again.

**Comment by RonaldBlom** [comment]
Sorry for late reply. 

Since we are in middle of net centric migration. All bd's we create are with unicast routing disabled. But with current fix it will not disable. We have a default which tries to configure is as disabled, but result is always: unicast routing enabled.

My current workaround is:
if not unicast_routing:
            payload.update(unicastRouting=unicast_routing)

This is working, but probably not ideal.

**Comment by RonaldBlom** [comment]
Good morning, I updated all collections again to latest and again I am not able to create a bridge domain with unicast disabled. Below you find the verbose output of the task:

changed: [hostname] => {
    "changed": true,
    "current": {
        "arpFlood": true,
        "dhcpLabels": [
            {
                "dhcpOptionLabel": null,
                "name": "dhcp_test_vpn_2_1.0.0.1",
                "version": 1
            },
            {
                "dhcpOptionLabel": null,
                "name": "dhcp_test_vpn_2_1.1.1.1",
                "version": 1
            }
        ],
        "displayName": "bd_10.0.6.1_24",
        "intersiteBumTrafficAllow": true,
        "l2Stretch": true,
        "l2UnknownUnicast": "flood",
        "multiDstPktAct": "bd-flood",
        "name": "bd_10.0.6.1_24",
        "subnets": [
            {
                "description": "10.0.6.1/24",
                "ip": "10.0.6.1/24",
                "noDefaultGateway": false,
                "primary": false,
                "querier": false,
                "scope": "public",
                "shared": false,
                "virtual": false
            }
        ],
        "vrfRef": {
            "schemaId": "62bbee022000003ff051ecb4",
            "templateName": "test_vpn_2_af91-af92",
            "vrfName": "test_vpn_2"
        }
    },
    "invocation": {
        "module_args": {
            "arp_flooding": true,
            "bd": "bd_10.0.6.1_24",
            "description": null,
            "dhcp_policies": [
                {
                    "dhcpOptionLabel": null,
                    "name": "dhcp_test_vpn_2_1.0.0.1",
                    "version": 1
                },
                {
                    "dhcpOptionLabel": null,
                    "name": "dhcp_test_vpn_2_1.1.1.1",
                    "version": 1
                }
            ],
            "dhcp_policy": null,
            "display_name": null,
            "host": "hostname",
            "intersite_bum_traffic": true,
            "ipv6_unknown_multicast_flooding": null,
            "layer2_stretch": true,
            "layer2_unknown_unicast": "flood",
            "layer3_multicast": null,
            "login_domain": "TACACS",
            "multi_destination_flooding": "flood_in_bd",
            "optimize_wan_bandwidth": null,
            "output_level": "normal",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "schema": "tenant_test_vpn_2",
            "state": "present",
            "subnets": [
                {
                    "description": "10.0.6.1/24",
                    "ip": "10.0.6.1/24",
                    "no_default_gateway": false,
                    "primary": false,
                    "querier": false,
                    "scope": "public",
                    "shared": false,
                    "subnet": "10.0.6.1/24",
                    "virtual": false
                }
            ],
            "template": "test_vpn_2_af91-af92",
            "timeout": 30,
            "unicast_routing": false,
            "unknown_multicast_flooding": null,
            "use_proxy": null,
            "use_ssl": null,
            "username": "username",
            "validate_certs": false,
            "virtual_mac_address": null,
            "vrf": {
                "name": "test_vpn_2",
                "schema": null,
                "template": null
            }
        }
    }
}

**Comment by RonaldBlom** [comment]
result of the above is, that unicast routing is enabled on the bd. Could you please check what is going wrong or what I am doing wrong?

**Comment by akinross** [comment]
create bd with unicast_routing set to "false" on first create does not work, toggling between true/false after and creating with true does work.

**Comment by lhercot** [comment]
This issue was fixed in PR #278 and the fix should be available in the next released version.

**Pull request closed without merging**
