### PR TITLE
Updated mso.mso_schema_template_anp_epg_contract query logic

### PR DESCRIPTION
**Pull request by justinbrink**
Small proposed fix for issue #523
DCNE-166

### CODE REVIEW

**Review by samiib — DISMISSED** [review]
LGTM

**Review by akinross — APPROVED** [review]
LGTM, added test for the issue

**Review by shrsr — APPROVED** [review]
LGTM

**Review by sajagana — APPROVED** [review]
LGTM!

**Review by lhercot — APPROVED** [review]
LGTM

**Pull request merged**
